# File Location: ~/.bash_profile
# Run the following to download and initialize:
# curl -o ~/.bash_profile https://raw.githubusercontent.com/mindovermiles262/dots/master/bash/bash_profile && source ~/.bash_profile

# ADDITION TESTING

# Load settings from .bashrc
[[ -r ~/.bashrc ]] && . ~/.bashrc

if [[ "$OSTYPE" == 'linux'* ]]; then
  alias linux-upgrade="sudo apt-get update \
    && sudo apt-get -y upgrade \
    && sudo apt-get -y dist-upgrade \
    && printf '\n\n' \
    && printf 'Linux Has Been Updated\n  {apt-get update}\n  {apt-get upgrade}\n  {apt-get dist-upgrade}\n'"
  
  # Add color to Terminal:
  export PS1="\e[44;1m \W \e[40;32m\$(parse_git_branch)\e[00m $ "
    # \e[44;30m              => Color definition
    # \W                     => Prints CWD
    # \e[40;32m              => Color definition
    # \$(parse_git_branch)   => Includes git branch
    # \e[00m                 => Default Color
    # $                      => Prompt Character

  
elif [[ "$OSTYPE" == "darwin17" ]]; then
  # Add color to OSX Terminal
  export CLICOLOR=1
  # export LSCOLORS=GxFxCxDxBxegedabagaced
  export PS1="\e[44;30m\W \e[40;32m\$(parse_git_branch)\e[00m $ "
fi

# Git branch in terminal.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# File Aliases
alias ll="ls -lha"
alias la="ls -lha"
alias l="ls -lh"

# Add Rails Aliases
alias reset="rails db:migrate:reset; rails db:seed"
alias migrate="rails db:migrate"
alias seed="rails db:seed"

# Editor Aliases
alias v="vim"
alias sv="sudo vim"
alias c="code ."

# Editing Bash Profile
alias vbash="vim ~/.bash_profile"
alias sbash="source ~/.bash_profile"

# Download VIM-Plug and initialize in ~/.vim/autoload, then download .vimrc
alias vim-init="printf 'Downloading Plug\n' \
  && curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
  && curl -o ~/.vimrc https://raw.githubusercontent.com/mindovermiles262/dots/master/vim/vimrc"

# Download and update program profiles
alias vim-update="printf 'Updating .vimrc file:\n' \
  && curl -o ~/.vimrc https://raw.githubusercontent.com/mindovermiles262/dots/master/vim/vimrc"
  
alias bash-update="curl -o ~/.bash_profile https://raw.githubusercontent.com/mindovermiles262/dots/master/bash/bash_profile \
  && source ~/.bash_profile \
  && clear \
  && printf 'Updated .bash_profile from Github\n'"

# Get current IP address
alias cip="curl https://andyduss.com/ip"



### - - - TO BE DELETED - - - ###
# Should be added to .bashrc instead

# Load RVM into a shell session *as a function*
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Add rbenv to PATH
# if [ -d "$HOME/.rbenv" ]; then
#   export PATH="$HOME/.rbenv/bin:$PATH"
#   eval "$(rbenv init -)"
# fi
