# File Location: ~/.bash_profile
# Run the following to download and initialize:
# curl -o ~/.bash_profile https://raw.githubusercontent.com/mindovermiles262/dots/master/bash/bash_profile

if [[ "$OSTYPE" == 'linux'* ]]; then
  printf "Hello Linux\n"
  alias linux-upgrade="sudo apt-get update \
    && sudo apt-get -y upgrade \
    && sudo apt-get -y dist-upgrade \
    && clear \
    && printf 'Linux Has Been Updated\n  {apt-get update}\n  {apt-get upgrade}\n  {apt-get dist-upgrade}\n'"
    
  # add email command to open inbox
  alias email="mail -f /home/student/email/"
  export MAIL=/home/student/email
  
  # add color to Terminal
  export PS1="\e[46;1;37m\W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "
  
elif [[ "$OSTYPE" == "darwin17" ]]; then
  printf "Hello Mac\n"
  
  # Add color to OSX Terminal
  export CLICOLOR=1
  export LSCOLORS=GxFxCxDxBxegedabagaced
  export PS1="\e[40;1m\W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "
  
  # Add Python3 to PATH
  export PATH=~/Library/Python/3.6/bin:$PATH
  
  # The next line updates PATH for the Google Cloud SDK.
  if [ -f '/usr/local/bin/google-cloud-sdk/path.bash.inc' ]; then source '/usr/local/bin/google-cloud-sdk/path.bash.inc'; fi

  # The next line enables shell command completion for gcloud.
  if [ -f '/usr/local/bin/google-cloud-sdk/completion.bash.inc' ]; then source '/usr/local/bin/google-cloud-sdk/completion.bash.inc'; fi
fi



# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Git branch in terminal.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# File Aliases
alias ll="ls -lha"
alias la="ls -lha"
alias l="ls -lh"

# Add Python Aliases
alias pip="pip3"
alias py="python3"

# Add Rails Aliases
alias reset="rails db:migrate:reset; rails db:seed"
alias migrate="rails db:migrate"
alias seed="rails db:seed"

# Editor Aliases
alias v="vim"
alias sv="sudo vim"
alias c="code ."

# Download VIM-Plug and initialize in ~/.vim/autoload, then download .vimrc
alias vim-init="printf 'Downloading Plug\n' \
  && curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
  && curl -o ~/.vimrc https://raw.githubusercontent.com/mindovermiles262/dots/master/vim/vimrc"

# Download and update program profiles
alias vim-update="printf 'Updating .vimrc file:\n' \
  && curl -o ~/.vimrc https://raw.githubusercontent.com/mindovermiles262/dots/master/vim/vimrc"
  
alias bash-update="curl -o ~/.bash_profile https://raw.githubusercontent.com/mindovermiles262/dots/master/bash/bash_profile \
  && source ~/.bash_profile \
  && clear \
  && printf 'Updated .bash_profile from Github\n'"

# SSH into servers
alias server="ssh student@207.246.64.67"
alias kodi="ssh osmc@73.189.217.34"
alias lk="ssh osmc@192.168.50.5"
